apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwo-single
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx-single
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
